# Spring Boot configuration
spring:
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: XXXX@gmail.com #Adicionar e-mail para testar funcionalidade de troca de senha
    password: XXXXXXXXXXX
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://Host:Port/pmsdb
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false

server:
  port: 8080
  error:
    whitelabel:
      enabled: false
